apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-v1
  template:
    metadata:
      labels:
        app: helloworld-v1
    spec:
      containers:
      - name: k8s-demo
        image: nginx
        ports:
        - name: nodejs-port
          containerPort: 3000
