apiVersion: v1
kind: Service
metadata:
  name: helloworld-v1
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30303
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: helloworld-v1
